[package]
org = "mevan"
name = "proxy_service"
version = "0.1.0"
distribution = "2201.9.0"

[build-options]
observabilityIncluded = true

[[platform.java17.dependency]]
groupId = "com.cossacklabs.com"
artifactId = "java-themis"
version = "0.15.2"

# transitive dependency of com.cossacklabs.com:java-themis:0.15.2
[[platform.java17.dependency]]
groupId = "org.jetbrains.kotlin"
artifactId = "kotlin-stdlib"
version = "1.4.32"

# transitive dependency of org.jetbrains.kotlin:kotlin-stdlib:1.4.32
[[platform.java17.dependency]]
groupId = "org.jetbrains.kotlin"
artifactId = "kotlin-stdlib-common"
version = "1.4.32"

# transitive dependency of org.jetbrains.kotlin:kotlin-stdlib:1.4.32
[[platform.java17.dependency]]
groupId = "org.jetbrains"
artifactId = "annotations"
version = "13.0"

# transitive dependency of com.cossacklabs.com:java-themis:0.15.2
[[platform.java17.dependency]]
groupId = "org.jetbrains"
artifactId = "annotations-java5"
version = "16.0.2"
